version: '3.8'

services: # Define services
  mongodb: # Service name
    image: mongo:8.0.1
    restart: always
    container_name: ${CONTAINER_NAME:-yx-chat-mongodb}
    ports: # Port mapping
      - '${MONGO_PORT:-27017}:27017' # Map host's port to container's port
    volumes: # Define volume mounts
      - mongo-data-dev:/data/db # Mount mongo-data-dev volume to container's /data/db
      - mongo-config-dev:/data/configdb # Mount mongo-config-dev volume to container's /data/configdb

volumes: # Define volumes
  mongo-data-dev:
    external: true # Use externally created volume
  mongo-config-dev:
    external: true # Use externally created volume
