export function getContentTypeByFilename(filename: string) {
  const extension = filename.split('.').pop()?.toLowerCase();
  switch (extension) {
    case 'jpg':
    case 'jpeg':
      return 'image/jpeg';
    case 'png':
      return 'image/png';
    case 'gif':
      return 'image/gif';
    case 'pdf':
      return 'application/pdf';
    case 'txt':
      return 'text/plain';
    case 'svg':
      return 'image/svg+xml';
    case 'webp':
      return 'image/webp';
    case 'json':
      return 'application/json';
    case 'xml':
      return 'application/xml';
    case 'html':
      return 'text/html';
    case 'css':
      return 'text/css';
    case 'js':
      return 'application/javascript';
    case 'mp4':
      return 'video/mp4';
    case 'mp3':
      return 'audio/mpeg';
    case 'wav':
      return 'audio/wav';
    case 'ogg':
      return 'audio/ogg';
    case 'webm':
      return 'video/webm';
    case 'zip':
      return 'application/zip';
    case 'rar':
      return 'application/x-rar-compressed';
    case 'tar':
      return 'application/x-tar';
    case 'gz':
      return 'application/gzip';
    case 'bz2':
      return 'application/x-bzip2';
    case '7z':
      return 'application/x-7z-compressed';
    case 'doc':
    case 'docx':
      return 'application/msword';
    case 'xls':
    case 'xlsx':
      return 'application/vnd.ms-excel';
    case 'ppt':
    case 'pptx':
      return 'application/vnd.ms-powerpoint';
    case 'csv':
      return 'text/csv';
    case 'ts':
      return 'application/typescript';
    case 'tsx':
      return 'application/tsx';
    case 'jsx':
      return 'application/jsx';
    case 'md':
      return 'text/markdown';
    case 'yml':
    case 'yaml':
      return 'text/yaml';
    case 'sh':
      return 'application/x-sh';
    case 'bat':
      return 'application/x-bat';
    case 'ps1':
    case 'psm1':
      return 'application/powershell';
    default:
      return 'application/octet-stream';
  }
}
